include:

   # base include - e.g.: network config
   - path:
      - ./docker-compose.include.#.yml

   # service + specific include
   - path:
      - ./registry/docker-compose.yml
      - ./docker-compose.include.registry.yml

   - path:
      - ./traefik/docker-compose.yml
      - ./docker-compose.include.traefik.yml

   - path:
      - ./whoami/docker-compose.yml
      - ./docker-compose.include.whoami.yml