services:

  traefik:

    image: traefik
    
    ports:
      - 80:80
      - 8080:8080
    
    command: 
      - --api.insecure=true 
      - --providers.docker

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock