services:

  traefik:

    image: registry.localhost/traefik
   
    ports:
      - 80:80
      - 8080:8080

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock

    healthcheck:
    # Run traefik healthcheck command
    # https://doc.traefik.io/traefik/operations/cli/#healthcheck
    # ! depends on: ping=true
      test: traefik healthcheck --ping
      timeout: 5s
      interval: 15s
      start_period: 10s
      retries: 3            